In [ ]:
import numpy as np 
data = np.load('data.npz')

# data have ampitude and phase differenc


data_list = []
for key in data.files:
    print(f"{key}:")
    print(data[key])
    data_list = data[key]

data_list


arr_0:
[[21.213203 24.04163  26.57066  ... 20.615528 19.849434 17.088007]
 [19.235384 23.769728 26.076809 ... 19.723083 19.697716 15.6205  ]
 [22.090721 24.698177 29.410883 ... 21.213203 21.587032 18.439089]
 ...
 [25.495098 24.083189 30.364452 ... 21.189621 25.495098 22.135944]
 [25.019993 24.698177 31.304953 ... 22.561028 24.04163  20.615528]
 [25.317978 23.769728 30.805843 ... 21.213203 24.839485 22.203604]]


array([[21.213203, 24.04163 , 26.57066 , ..., 20.615528, 19.849434,
        17.088007],
       [19.235384, 23.769728, 26.076809, ..., 19.723083, 19.697716,
        15.6205  ],
       [22.090721, 24.698177, 29.410883, ..., 21.213203, 21.587032,
        18.439089],
       ...,
       [25.495098, 24.083189, 30.364452, ..., 21.189621, 25.495098,
        22.135944],
       [25.019993, 24.698177, 31.304953, ..., 22.561028, 24.04163 ,
        20.615528],
       [25.317978, 23.769728, 30.805843, ..., 21.213203, 24.839485,
        22.203604]], shape=(374584, 90), dtype=float32)