# Numpy

Provided the support for arrays and matrices.

In [2]:
!pip install numpy

In [ ]:
import numpy as np

#create a array

arr1 = np.array([1,2,3,4,5]) # 1-D array
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4])
res_arr2 = arr2.reshape(1,4) # 1 row and 5 collumns
print(res_arr2.shape)

(1, 4)


In [12]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [14]:
# ones(x,y) -> create array with x row and y columns

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# to create identity mattrix

np.eye((3)) # create an identity mattrix of order 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
## Numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition

print("Addition : ", arr1+arr2)

# element wise substraction

print("Substraction : ", arr2 - arr1)

Addition :  [11 22 33 44 55]
Substraction :  [ 9 18 27 36 45]


In [22]:
# Universal function

arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.log(arr))
print("expo",np.exp(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
expo [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [ ]:
# Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)
arr[0][1]


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(2)

In [41]:
# Fix: Use only two indices for 2D array slicing
print(arr[1:, 2:])
print("hi",arr[0:2, 2:])
print(arr[1: , 1:3])

[[ 7  8]
 [11 12]]
hi [[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [42]:
# Modify array elements 
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [45]:
arr[1:] = 100
print(arr)
print(arr.shape)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
(3, 4)


In [46]:
# Statistical concepts - Normalization
# to have mean of 0 and SD of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized data : ", normalized_data)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
# calculate mean median mode variance

data1 = np.array([1,2,3,4,5,6,7,8])
mean = np.mean(data1)
median = np.median(data1)
variance = np.var(data1)
std_dev = np.std(data1)
print("mean", mean)
print("median", median)
print("variance", variance)
print("std dev", std_dev)
mode = 3*median - 2*mean
print("mode",mode)

mean 4.5
median 4.5
variance 5.25
std dev 2.29128784747792
mode 4.5


In [ ]:
# Logical operations 
data = np.array([1,2,3,4,5,6,7,8,9])
data > 5
data[(data > 5) & (data <= 8)]  # applying indexing here

array([6, 7, 8])